---
Documentation:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: true
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
EmptyLinesAroundBlockBody:
  Enabled: false
MethodLength:
  Max: 40
NumericLiterals:
  MinDigits: 10
Metrics/BlockLength:
  Max: 40
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 30
# temporary deactivated
Style/PercentLiteralDelimiters:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
